services:
  web:
    image: atlantys/platform-backend:latest
    container_name: platform-backend
    command: "alembic upgrade head "
    ports:
      - "9000:9000"
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - .:/app
    depends_on:
      - postgres
      
  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=platform-db
    ports:
      - "5432:5432"

  worker:
    build: .
    command: python -m dramatiq src.core.dramtiq_worker
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app_network


networks:
  app_network:
    external: true


volumes:
  postgres_data: