services:
  web:
    build: .
    container_name: platform-backend
    command: python -u main.py
    ports:
      - "9000:9000"
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - .:/app
    depends_on:
      - postgres

  telegram-bot:
    build: .
    container_name: telegram_bot
    restart: always
    env_file:
      - .env
    networks:
      - app_network
    ports:
      - "9010:9010"

  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: atlantys
      POSTGRES_PASSWORD: atlantysatlantys
      POSTGRES_DB: platform_db
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "atlantys"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build: .
    container_name: worker
    command: python -m dramatiq src.core.dramatiq_worker --processes 3 --threads 4
    env_file:
      - .env
    networks:
      - app_network
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres
    deploy:
      resources:
        limits:
          memory: "3GB"
          cpus: "3.0"


  redis:
    image: redis:alpine
    container_name: redis_container
    command: redis-server --maxmemory 1gb --maxmemory-policy allkeys-lru --save "" --appendonly no
    ports:
      - "6380:6379"
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: "1GB"


  minio:
      image: quay.io/minio/minio
      container_name: minio
      command: server /data --console-address ":9001"
      ports:
        - "9002:9000" # S3 API порт
        - "9003:9001" # Консоль MinIO
      environment:
        - MINIO_ROOT_USER=admin
        - MINIO_ROOT_PASSWORD=admin123
      volumes:
        - minio_data:/data
      networks:
        - app_network


  celery-worker:
      build: .
      command: celery -A src.core.celery_config worker --loglevel=info
      env_file:
      - .env

      volumes:
        - .:/app
      depends_on:
        - postgres
        - redis
      environment:
        - PYTHONPATH=/app/src
      networks:
        - app_network
  celery-beat:
    build: .
    command: celery -A src.core.celery_config worker --loglevel=info    
    environment:
      - PYTHONPATH=/app/src
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - postgres
      - redis
      - celery-worker
    networks:
        - app_network

networks:
  app_network:
    external: true

volumes:
  postgres_data:
  minio_data: