"""user feedback

Revision ID: 03cc998a7faa
Revises: 560d014281d1
Create Date: 2025-01-24 06:10:40.013582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03cc998a7faa'
down_revision: Union[str, None] = '560d014281d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_feedbacks', sa.Column('user_organization', sa.String(), nullable=True
    ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_feedbacks', 'user_organization')
    # ### end Alembic commands ###
