"""created new fields into user interaction

Revision ID: 04bbf0a0b76a
Revises: cc22492e12f6
Create Date: 2025-04-10 17:45:46.081535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bbf0a0b76a'
down_revision: Union[str, None] = 'cc22492e12f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interactions', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('user_interactions', sa.Column('is_last', sa.Boolean(), nullable=True, default=True))
    op.create_foreign_key(None, 'user_interactions', 'assistant_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_interactions', type_='foreignkey')
    op.drop_column('user_interactions', 'is_last')
    op.drop_column('user_interactions', 'session_id')
    # ### end Alembic commands ###
