"""fix user-role table

Revision ID: 0b4a01947eef
Revises: f30ae4b2ffa0
Create Date: 2024-12-05 14:42:43.615427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4a01947eef'
down_revision: Union[str, None] = 'f30ae4b2ffa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organization_members_role_id_fkey', 'organization_members', type_='foreignkey')
    op.drop_column('organization_members', 'role_id')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    op.add_column('organization_members', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('organization_members_role_id_fkey', 'organization_members', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
