"""fix: favorite_resumes

Revision ID: 1e035ceeca2f
Revises: 20b3e2063577
Create Date: 2025-03-12 10:46:53.343770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e035ceeca2f'
down_revision: Union[str, None] = '20b3e2063577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_resumes', sa.Column('call_sid', sa.String(), nullable=True))
    op.add_column('favorite_resumes', sa.Column('is_called', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_resumes', 'is_called')
    op.drop_column('favorite_resumes', 'call_sid')
    # ### end Alembic commands ###
