"""fix: favorite_resumes

Revision ID: 20b3e2063577
Revises: f6d60644c5ba
Create Date: 2025-03-12 09:37:18.298836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20b3e2063577'
down_revision: Union[str, None] = 'f6d60644c5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_clones_id', table_name='ai_clones')
    op.drop_table('ai_clones')
    op.add_column('favorite_resumes', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('favorite_resumes', sa.Column('recording_file', sa.String(), nullable=True))
    op.add_column('favorite_resumes', sa.Column('is_responded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_resumes', 'is_responded')
    op.drop_column('favorite_resumes', 'recording_file')
    op.drop_column('favorite_resumes', 'phone_number')
    op.create_table('ai_clones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agreement_video_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sample_video_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lipsynch_text', sa.VARCHAR(length=3000), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_clones_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ai_clones_pkey')
    )
    op.create_index('ix_ai_clones_id', 'ai_clones', ['id'], unique=False)
    # ### end Alembic commands ###
