"""whatsapp instance table is changed

Revision ID: 2116e04353c6
Revises: e0646daa2a46
Create Date: 2025-04-05 22:35:04.036721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2116e04353c6'
down_revision: Union[str, None] = 'e0646daa2a46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_instance_association', sa.Column('whatsapp_instance_id', sa.Integer(), nullable=False))
    op.drop_constraint('user_instance_association_instance_id_fkey', 'user_instance_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_instance_association', 'whatsapp_instances', ['whatsapp_instance_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_instance_association', 'instance_id')
    op.add_column('whatsapp_instances', sa.Column('instance_token', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_instances', 'instance_token')
    op.add_column('user_instance_association', sa.Column('instance_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_instance_association', type_='foreignkey')
    op.create_foreign_key('user_instance_association_instance_id_fkey', 'user_instance_association', 'whatsapp_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_instance_association', 'whatsapp_instance_id')
    op.drop_constraint('_user_whatsapp_instance_id_uc', 'current_whatsapp_instance', type_='unique')
    # ### end Alembic commands ###
