"""fix ChatMessageHistory

Revision ID: 22a8884a9c31
Revises: c4f17e272805
Create Date: 2025-01-21 08:58:58.471856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a8884a9c31'
down_revision: Union[str, None] = 'c4f17e272805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history_messages', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('chat_history_messages', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history_messages', 'updated_at')
    op.drop_column('chat_history_messages', 'created_at')
    # ### end Alembic commands ###
