"""feat: refund application

Revision ID: 24e6e1f6a490
Revises: 7f5cdf32db82
Create Date: 2025-02-05 11:37:54.486107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e6e1f6a490'
down_revision: Union[str, None] = '7f5cdf32db82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
