"""billing transaction was updated

Revision ID: 29a0c775c1df
Revises: f4145295783b
Create Date: 2025-03-31 16:57:45.858010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29a0c775c1df'
down_revision: Union[str, None] = 'f4145295783b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_clones_id', table_name='ai_clones')
    op.drop_table('ai_clones')
    op.drop_column('balances', 'subscription')
    op.add_column('billing_transactions', sa.Column('promo_id', sa.Integer(), nullable=True))
    op.execute("ALTER TABLE billing_transactions ALTER COLUMN subscription_id TYPE INTEGER USING subscription_id::integer")
    op.create_foreign_key(None, 'billing_transactions', 'promocodes', ['promo_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'billing_transactions', 'subscriptions', ['subscription_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'billing_transactions', type_='foreignkey')
    op.drop_constraint(None, 'billing_transactions', type_='foreignkey')
    op.alter_column('billing_transactions', 'subscription_id',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_column('billing_transactions', 'promo_id')
    op.add_column('balances', sa.Column('subscription', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('ai_clones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('agreement_video_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sample_video_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lipsynch_text', sa.VARCHAR(length=3000), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='ai_clones_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ai_clones_pkey')
    )
    op.create_index('ix_ai_clones_id', 'ai_clones', ['id'], unique=False)
    # ### end Alembic commands ###
