"""fix hr tasks

Revision ID: 29ac2974ce22
Revises: c0c8d596ea8f
Create Date: 2025-01-22 11:12:32.430154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ac2974ce22'
down_revision: Union[str, None] = 'c0c8d596ea8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_assistant_tasks', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_assistant_tasks', 'file_url')
    # ### end Alembic commands ###
