"""fix: organization table

Revision ID: 2a0c9a29096a
Revises: 137836e6d953
Create Date: 2024-12-06 14:26:44.898428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0c9a29096a'
down_revision: Union[str, None] = '137836e6d953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('organization_members_employer_id_fkey', 'organization_members', type_='foreignkey')
    op.create_foreign_key(None, 'organization_members', 'users', ['user_id'], ['id'])
    op.drop_column('organization_members', 'employer_id')
    op.drop_constraint('organizations_admin_id_key', 'organizations', type_='unique')
    op.drop_constraint('organizations_admin_id_fkey', 'organizations', type_='foreignkey')
    op.drop_column('organizations', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('organizations_admin_id_fkey', 'organizations', 'users', ['admin_id'], ['id'])
    op.create_unique_constraint('organizations_admin_id_key', 'organizations', ['admin_id'])
    op.add_column('organization_members', sa.Column('employer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.create_foreign_key('organization_members_employer_id_fkey', 'organization_members', 'users', ['employer_id'], ['id'])
    op.drop_column('organization_members', 'user_id')
    # ### end Alembic commands ###
