"""add is verified field

Revision ID: 2b05461f3af1
Revises: 938a9ed5d14a
Create Date: 2025-01-16 10:05:17.258855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b05461f3af1'
down_revision: Union[str, None] = '938a9ed5d14a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_sessions', 'is_archived')
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.add_column('assistant_sessions', sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
