"""fix: HRTask

Revision ID: 2f17b2f4ae90
Revises: ca552a674deb
Create Date: 2025-01-14 06:21:33.065919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f17b2f4ae90'
down_revision: Union[str, None] = 'ca552a674deb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_assistant_tasks', sa.Column('text_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_assistant_tasks', 'text_hash')
    # ### end Alembic commands ###
