"""fix: unique constraint

Revision ID: 3e80bb5f9785
Revises: c67cebc2f372
Create Date: 2025-02-06 12:09:52.813778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e80bb5f9785'
down_revision: Union[str, None] = 'c67cebc2f372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'balances', ['organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balances', type_='unique')
    # ### end Alembic commands ###
