"""type balance usage 

Revision ID: 3ec7bc2d924f
Revises: 3e80bb5f9785
Create Date: 2025-02-06 13:18:28.488044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ec7bc2d924f'
down_revision: Union[str, None] = '3e80bb5f9785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_usage', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balance_usage', 'type')
    # ### end Alembic commands ###
