"""fix: is_archived Vacancy

Revision ID: 405d79ae1ba7
Revises: f53da9dacf1a
Create Date: 2024-12-30 08:47:03.060894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '405d79ae1ba7'
down_revision: Union[str, None] = 'f53da9dacf1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy', 'is_archived')
    # ### end Alembic commands ###
