"""user feedbacks

Revision ID: 560d014281d1
Revises: 9f8af5f11523
Create Date: 2025-01-23 10:35:28.132211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '560d014281d1'
down_revision: Union[str, None] = '9f8af5f11523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedbacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('experience_rating', sa.Float(), nullable=False),
    sa.Column('vacancy_creation_rating', sa.Float(), nullable=False),
    sa.Column('resume_analysis_rating', sa.Float(), nullable=False),
    sa.Column('improvements', sa.Text(), nullable=True),
    sa.Column('vacancy_price', sa.Text(), nullable=True),
    sa.Column('resume_analysis_price', sa.Text(), nullable=True),
    sa.Column('free_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_feedbacks_id'), 'user_feedbacks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_feedbacks_id'), table_name='user_feedbacks')
    op.drop_table('user_feedbacks')
    # ### end Alembic commands ###
