"""created candidante info table

Revision ID: 5bb8499011d4
Revises: f81b375aafed
Create Date: 2025-04-14 18:11:52.044683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bb8499011d4'
down_revision: Union[str, None] = 'f81b375aafed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_info', sa.JSON(), nullable=True),
    sa.Column('resume_url', sa.String(), nullable=True),
    sa.Column('hh_resume_url', sa.String(), nullable=True),
    sa.Column('is_hh', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user_interactions', sa.Column('is_hh', sa.Boolean(), nullable=True))
    op.add_column('user_interactions', sa.Column('is_whatsapp', sa.Boolean(), nullable=True))
    op.drop_column('user_interactions', 'message_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interactions', sa.Column('message_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user_interactions', 'is_whatsapp')
    op.drop_column('user_interactions', 'is_hh')
    op.drop_table('candidate_info')
    # ### end Alembic commands ###
