"""add relationship between Vacancy and AssitantSession

Revision ID: 5c8b6b77be44
Revises: 405d79ae1ba7
Create Date: 2025-01-13 08:54:17.897898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c8b6b77be44'
down_revision: Union[str, None] = '405d79ae1ba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy', sa.Column('session_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'vacancy', 'assistant_sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy', type_='foreignkey')
    op.drop_column('vacancy', 'session_id')
    # ### end Alembic commands ###
