"""organization subscription table fixed

Revision ID: 64da1c073620
Revises: 2116e04353c6
Create Date: 2025-04-06 19:26:32.678042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64da1c073620'
down_revision: Union[str, None] = '2116e04353c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_organization_subscriptions_organization_id'), 'organization_subscriptions', ['organization_id'], unique=False)
    op.drop_constraint('organization_subscriptions_promo_id_fkey', 'organization_subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'organization_subscriptions', 'promocodes', ['promo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_subscriptions', type_='foreignkey')
    op.create_foreign_key('organization_subscriptions_promo_id_fkey', 'organization_subscriptions', 'promocodes', ['promo_id'], ['id'])
    op.drop_index(op.f('ix_organization_subscriptions_organization_id'), table_name='organization_subscriptions')
    op.drop_constraint('_user_whatsapp_instance_id_uc', 'current_whatsapp_instance', type_='unique')
    # ### end Alembic commands ###
