"""Adas

Revision ID: 668d09f2ec9a
Revises: 7b537d3f3d16
Create Date: 2025-03-04 11:18:37.339270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668d09f2ec9a'
down_revision: Union[str, None] = '7b537d3f3d16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_resumes', sa.Column('session_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'favorite_resumes', 'assistant_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite_resumes', type_='foreignkey')
    op.drop_column('favorite_resumes', 'session_id')
    # ### end Alembic commands ###
