"""add hh pdf url

Revision ID: 7afc17049442
Revises: 6ed7df35e889
Create Date: 2025-02-13 12:22:06.025955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7afc17049442'
down_revision: Union[str, None] = '6ed7df35e889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_assistant_tasks', sa.Column('hh_file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hr_assistant_tasks', 'hh_file_url')
    # ### end Alembic commands ###
