"""fix: Clone table

Revision ID: 7b537d3f3d16
Revises: 4b55a040693c
Create Date: 2025-02-21 09:56:41.829101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b537d3f3d16'
down_revision: Union[str, None] = '4b55a040693c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_clones', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('ai_clones', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_clones', 'name')
    op.drop_column('ai_clones', 'gender')
    # ### end Alembic commands ###
