"""transaction id

Revision ID: 7f5cdf32db82
Revises: 88af2a971a24
Create Date: 2025-02-05 06:07:50.822445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f5cdf32db82'
down_revision: Union[str, None] = '88af2a971a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_transactions', sa.Column('type', sa.String(), nullable=True))
    op.add_column('billing_transactions', sa.Column('bank_transaction_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_transactions', 'bank_transaction_id')
    op.drop_column('billing_transactions', 'type')
    # ### end Alembic commands ###
