"""fix organization table

Revision ID: 8878f685aaef
Revises: ac62758a2e84
Create Date: 2024-12-17 09:18:39.438989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8878f685aaef'
down_revision: Union[str, None] = 'ac62758a2e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('email', sa.String(), nullable=False))
    op.add_column('organizations', sa.Column('phone_number', sa.String(), nullable=True))
    op.alter_column('organizations', 'registered_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('organizations', 'contact_information')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('contact_information', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('organizations', 'registered_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('organizations', 'phone_number')
    op.drop_column('organizations', 'email')
    # ### end Alembic commands ###
