"""fix billing transactions

Revision ID: 88af2a971a24
Revises: b3cddf3505bb
Create Date: 2025-02-03 12:41:34.064174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88af2a971a24'
down_revision: Union[str, None] = 'b3cddf3505bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_transactions', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('billing_transactions', sa.Column('invoice_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_transactions', 'invoice_id')
    op.drop_column('billing_transactions', 'access_token')
    # ### end Alembic commands ###
