"""hh tokens

Revision ID: 898327feb47c
Revises: a23f80cde550
Create Date: 2025-02-12 09:40:39.653834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '898327feb47c'
down_revision: Union[str, None] = 'a23f80cde550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hh_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hh_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hh_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hh_token_expires_at')
    op.drop_column('users', 'hh_refresh_token')
    op.drop_column('users', 'hh_access_token')
    # ### end Alembic commands ###
