"""CASCADE delete

Revision ID: 8af7331b12e6
Revises: 2b05461f3af1
Create Date: 2025-01-17 06:32:38.478462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af7331b12e6'
down_revision: Union[str, None] = '2b05461f3af1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint('vacancy_session_id_fkey', 'vacancy', type_='foreignkey')
    op.create_foreign_key(None, 'vacancy', 'assistant_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancy', type_='foreignkey')
    op.create_foreign_key('vacancy_session_id_fkey', 'vacancy', 'assistant_sessions', ['session_id'], ['id'])
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
