"""add: Vacancy Requirement

Revision ID: 938a9ed5d14a
Revises: 2f17b2f4ae90
Create Date: 2025-01-14 06:50:35.900294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '938a9ed5d14a'
down_revision: Union[str, None] = '2f17b2f4ae90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_requirements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('requirement_hash', sa.String(), nullable=False),
    sa.Column('requirement_text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['assistant_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_requirements_requirement_hash'), 'vacancy_requirements', ['requirement_hash'], unique=False)
    op.create_index(op.f('ix_vacancy_requirements_requirement_text'), 'vacancy_requirements', ['requirement_text'], unique=False)
    op.create_index(op.f('ix_hr_assistant_tasks_text_hash'), 'hr_assistant_tasks', ['text_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_assistant_tasks_text_hash'), table_name='hr_assistant_tasks')
    op.drop_index(op.f('ix_vacancy_requirements_requirement_text'), table_name='vacancy_requirements')
    op.drop_index(op.f('ix_vacancy_requirements_requirement_hash'), table_name='vacancy_requirements')
    op.drop_table('vacancy_requirements')
    # ### end Alembic commands ###
