"""HRTask table tokens_spent column

Revision ID: 9d7d939d5299
Revises: 3c5afe8f5d07
Create Date: 2024-12-25 23:28:14.131017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7d939d5299'
down_revision: Union[str, None] = '3c5afe8f5d07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_assistant_tasks', sa.Column('tokens_spent', sa.Integer(), nullable=True))
    op.alter_column('vacancy', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancy', 'title',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('hr_assistant_tasks', 'tokens_spent')
    # ### end Alembic commands ###
