"""created new table for track interview task

Revision ID: 9f6588559198
Revises: 04bbf0a0b76a
Create Date: 2025-04-11 14:23:05.856418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f6588559198'
down_revision: Union[str, None] = '04bbf0a0b76a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_generate_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILURE', name='generatestatus'), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('interview_individual_questions_session_id_fkey', 'interview_individual_questions', type_='foreignkey')
    op.drop_column('interview_individual_questions', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_individual_questions', sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('interview_individual_questions_session_id_fkey', 'interview_individual_questions', 'assistant_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_table('resume_generate_session')
    # ### end Alembic commands ###
