"""fix hr tasks

Revision ID: 9f8af5f11523
Revises: 29ac2974ce22
Create Date: 2025-01-23 06:23:51.828240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f8af5f11523'
down_revision: Union[str, None] = '29ac2974ce22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_assistant_tasks', sa.Column('file_key', sa.String(), nullable=True))
    op.drop_column('hr_assistant_tasks', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr_assistant_tasks', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('hr_assistant_tasks', 'file_key')
    # ### end Alembic commands ###
