"""biling balance

Revision ID: a79e96dfb0ac
Revises: b744db4a3e50
Create Date: 2025-01-30 10:13:38.389747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a79e96dfb0ac'
down_revision: Union[str, None] = 'b744db4a3e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('balance_id', sa.Integer(), nullable=False),
    sa.Column('input_text_count', sa.Integer(), nullable=False),
    sa.Column('gpt_token_spent', sa.Integer(), nullable=False),
    sa.Column('input_token_count', sa.Integer(), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('atl_token_spent', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['balance_id'], ['balances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balance_usage_id'), 'balance_usage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balance_usage_id'), table_name='balance_usage')
    op.drop_table('balance_usage')
    # ### end Alembic commands ###
