"""add clone

Revision ID: aa4dc3aaa8d5
Revises: 7afc17049442
Create Date: 2025-02-20 07:43:26.602878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4dc3aaa8d5'
down_revision: Union[str, None] = '7afc17049442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_clones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('agreement_video_path', sa.String(), nullable=False),
    sa.Column('sample_video_path', sa.String(), nullable=False),
    sa.Column('lipsynch_text', sa.String(length=3000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_clones_id'), 'ai_clones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_clones_id'), table_name='ai_clones')
    op.drop_table('ai_clones')
    # ### end Alembic commands ###
