"""fix: assistant id

Revision ID: b3cddf3505bb
Revises: a79e96dfb0ac
Create Date: 2025-01-31 11:39:25.149594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3cddf3505bb'
down_revision: Union[str, None] = 'a79e96dfb0ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_usage', sa.Column('assistant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'balance_usage', 'assistants', ['assistant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'balance_usage', type_='foreignkey')
    op.drop_column('balance_usage', 'assistant_id')
    # ### end Alembic commands ###
