"""created new table

Revision ID: be559411f244
Revises: b5d450aa425f
Create Date: 2025-04-07 15:06:50.849021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be559411f244'
down_revision: Union[str, None] = 'b5d450aa425f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('is_answered', sa.Boolean(), nullable=False),
    sa.Column('chosen_button', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_interactions')
    # ### end Alembic commands ###
