"""fix: cascade del for user and org members

Revision ID: c8fbd8b6d975
Revises: 2a0c9a29096a
Create Date: 2024-12-09 15:06:08.155549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8fbd8b6d975'
down_revision: Union[str, None] = '2a0c9a29096a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organization_members_user_id_fkey', 'organization_members', type_='foreignkey')
    op.drop_constraint('organization_members_organization_id_fkey', 'organization_members', type_='foreignkey')
    op.create_foreign_key(None, 'organization_members', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'organization_members', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.drop_constraint(None, 'organization_members', type_='foreignkey')
    op.create_foreign_key('organization_members_organization_id_fkey', 'organization_members', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key('organization_members_user_id_fkey', 'organization_members', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
