"""added new column

Revision ID: cc22492e12f6
Revises: d29f3904a548
Create Date: 2025-04-09 18:37:25.787298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc22492e12f6'
down_revision: Union[str, None] = 'd29f3904a548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interactions', sa.Column('instance_id', sa.Integer(), nullable=True))
    op.add_column('user_interactions', sa.Column('messages', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'user_interactions', 'whatsapp_instances', ['instance_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_interactions', 'chosen_button')
    op.drop_column('user_interactions', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interactions', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_interactions', sa.Column('chosen_button', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_interactions', type_='foreignkey')
    op.drop_column('user_interactions', 'messages')
    op.drop_column('user_interactions', 'instance_id')
    # ### end Alembic commands ###
