"""fav resume

Revision ID: d6907ebad187
Revises: 668d09f2ec9a
Create Date: 2025-03-04 11:42:40.567197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6907ebad187'
down_revision: Union[str, None] = '668d09f2ec9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_resumes', sa.Column('question_for_candidate', sa.JSON(), nullable=True))
    op.add_column('favorite_resumes', sa.Column('stage', sa.String(), nullable=True))
    op.alter_column('favorite_resumes', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('favorite_resumes', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('favorite_resumes', 'stage')
    op.drop_column('favorite_resumes', 'question_for_candidate')
    # ### end Alembic commands ###
