"""modified some tables

Revision ID: e0646daa2a46
Revises: f608a75ac83b
Create Date: 2025-04-04 17:30:41.402420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0646daa2a46'
down_revision: Union[str, None] = 'f608a75ac83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('_user_whatsapp_instance_id_uc', 'current_whatsapp_instance', ['user_id', 'whatsapp_instance_id'])
    op.add_column('whatsapp_instances', sa.Column('instance_id', sa.String(), nullable=False))
    op.add_column('whatsapp_instances', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_instances', 'is_active')
    op.drop_column('whatsapp_instances', 'instance_id')
    op.drop_constraint('_user_whatsapp_instance_id_uc', 'current_whatsapp_instance', type_='unique')
    # ### end Alembic commands ###
