"""hh tokens models

Revision ID: eeb4d77c0dc3
Revises: 898327feb47c
Create Date: 2025-02-12 09:53:04.317045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eeb4d77c0dc3'
down_revision: Union[str, None] = '898327feb47c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hh_token_expires_at')
    op.drop_column('users', 'hh_refresh_token')
    op.drop_column('users', 'hh_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hh_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hh_refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('hh_token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
