"""fix: is_archived AssistantSession

Revision ID: f53da9dacf1a
Revises: b22582ef023f
Create Date: 2024-12-30 07:52:00.686555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53da9dacf1a'
down_revision: Union[str, None] = 'b22582ef023f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_sessions', sa.Column('is_archived', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_sessions', 'is_archived')

    # ### end Alembic commands ###
