"""fix balance

Revision ID: f6d60644c5ba
Revises: ca9b0f88eb55
Create Date: 2025-03-07 12:49:17.845927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6d60644c5ba'
down_revision: Union[str, None] = 'ca9b0f88eb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('free_trial', sa.Boolean(), nullable=True))
    op.execute("UPDATE balances SET free_trial = FALSE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('balances', 'free_trial')
    # ### end Alembic commands ###
