"""resume id link is rebased

Revision ID: f81b375aafed
Revises: fa6a2d572207
Create Date: 2025-04-14 10:50:26.724613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f81b375aafed'
down_revision: Union[str, None] = 'fa6a2d572207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('interview_individual_questions_resume_id_fkey', 'interview_individual_questions', type_='foreignkey')
    op.create_foreign_key(None, 'interview_individual_questions', 'favorite_resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_individual_questions', type_='foreignkey')
    op.create_foreign_key('interview_individual_questions_resume_id_fkey', 'interview_individual_questions', 'hr_assistant_tasks', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
