"""added new field to user interaction

Revision ID: fa6a2d572207
Revises: 19ab79fdb59c
Create Date: 2025-04-14 10:35:53.211409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa6a2d572207'
down_revision: Union[str, None] = '19ab79fdb59c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interactions', sa.Column('is_ignored', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_interactions', 'is_ignored')
    # ### end Alembic commands ###
