"""fix organization table

Revision ID: fd735ac7d4fe
Revises: 6c4073e71b74
Create Date: 2024-12-05 15:50:56.437039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd735ac7d4fe'
down_revision: Union[str, None] = '6c4073e71b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('contact_information', sa.String(), nullable=False))
    op.add_column('organizations', sa.Column('registered_address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'registered_address')
    op.drop_column('organizations', 'contact_information')
    # ### end Alembic commands ###
